version: "3.9"

services:
  backend:
    build:
      context: ./astar/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./astar/backend/db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=1
    networks:
      - app-network

  frontend:
    build:
      context: ./Juzeng_react/juzeng_app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"    # Expose HTTP
      - "443:443"  # Expose HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
